2023-02-25 11:15:33,118 ERROR: Exception on / [GET] [in /Users/pauldobrowsky/Projects/microblog/venv/lib/python3.9/site-packages/flask/app.py:1741]
Traceback (most recent call last):
  File "/Users/pauldobrowsky/Projects/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/pauldobrowsky/Projects/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/pauldobrowsky/Projects/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/pauldobrowsky/Projects/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/pauldobrowsky/Projects/microblog/venv/lib/python3.9/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/Users/pauldobrowsky/Projects/microblog/app/routes.py", line 41, in index
    return render_template('index.html', title='Home', posts=posts)
  File "/Users/pauldobrowsky/Projects/microblog/venv/lib/python3.9/site-packages/flask/templating.py", line 147, in render_template
    return _render(app, template, context)
  File "/Users/pauldobrowsky/Projects/microblog/venv/lib/python3.9/site-packages/flask/templating.py", line 130, in _render
    rv = template.render(context)
  File "/Users/pauldobrowsky/Projects/microblog/venv/lib/python3.9/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/Users/pauldobrowsky/Projects/microblog/venv/lib/python3.9/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/pauldobrowsky/Projects/microblog/app/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/pauldobrowsky/Projects/microblog/app/templates/base.html", line 30, in top-level template code
    {% block content %}{% endblock %}
  File "/Users/pauldobrowsky/Projects/microblog/app/templates/index.html", line 6, in block 'content'
    {{ form.hidden_tag() }}
  File "/Users/pauldobrowsky/Projects/microblog/venv/lib/python3.9/site-packages/jinja2/environment.py", line 485, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
2023-02-25 11:15:33,240 ERROR: Exception on / [GET] [in /Users/pauldobrowsky/Projects/microblog/venv/lib/python3.9/site-packages/flask/app.py:1741]
Traceback (most recent call last):
  File "/Users/pauldobrowsky/Projects/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/pauldobrowsky/Projects/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/pauldobrowsky/Projects/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/pauldobrowsky/Projects/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/pauldobrowsky/Projects/microblog/venv/lib/python3.9/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/Users/pauldobrowsky/Projects/microblog/app/routes.py", line 41, in index
    return render_template('index.html', title='Home', posts=posts)
  File "/Users/pauldobrowsky/Projects/microblog/venv/lib/python3.9/site-packages/flask/templating.py", line 147, in render_template
    return _render(app, template, context)
  File "/Users/pauldobrowsky/Projects/microblog/venv/lib/python3.9/site-packages/flask/templating.py", line 130, in _render
    rv = template.render(context)
  File "/Users/pauldobrowsky/Projects/microblog/venv/lib/python3.9/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/Users/pauldobrowsky/Projects/microblog/venv/lib/python3.9/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/pauldobrowsky/Projects/microblog/app/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/pauldobrowsky/Projects/microblog/app/templates/base.html", line 30, in top-level template code
    {% block content %}{% endblock %}
  File "/Users/pauldobrowsky/Projects/microblog/app/templates/index.html", line 6, in block 'content'
    {{ form.hidden_tag() }}
  File "/Users/pauldobrowsky/Projects/microblog/venv/lib/python3.9/site-packages/jinja2/environment.py", line 485, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
2023-02-25 11:15:34,566 ERROR: Exception on / [GET] [in /Users/pauldobrowsky/Projects/microblog/venv/lib/python3.9/site-packages/flask/app.py:1741]
Traceback (most recent call last):
  File "/Users/pauldobrowsky/Projects/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/pauldobrowsky/Projects/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/pauldobrowsky/Projects/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/pauldobrowsky/Projects/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/pauldobrowsky/Projects/microblog/venv/lib/python3.9/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/Users/pauldobrowsky/Projects/microblog/app/routes.py", line 41, in index
    return render_template('index.html', title='Home', posts=posts)
  File "/Users/pauldobrowsky/Projects/microblog/venv/lib/python3.9/site-packages/flask/templating.py", line 147, in render_template
    return _render(app, template, context)
  File "/Users/pauldobrowsky/Projects/microblog/venv/lib/python3.9/site-packages/flask/templating.py", line 130, in _render
    rv = template.render(context)
  File "/Users/pauldobrowsky/Projects/microblog/venv/lib/python3.9/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/Users/pauldobrowsky/Projects/microblog/venv/lib/python3.9/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/pauldobrowsky/Projects/microblog/app/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/pauldobrowsky/Projects/microblog/app/templates/base.html", line 30, in top-level template code
    {% block content %}{% endblock %}
  File "/Users/pauldobrowsky/Projects/microblog/app/templates/index.html", line 6, in block 'content'
    {{ form.hidden_tag() }}
  File "/Users/pauldobrowsky/Projects/microblog/venv/lib/python3.9/site-packages/jinja2/environment.py", line 485, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
2023-02-25 23:06:59,081 INFO: Microblog startup [in /Users/pauldobrowsky/Projects/microblog/app/__init__.py:55]
